version: 3.8

services:
  django:
    build: ./
    env_file:
      - .env
    container_name: django-gisa
    restart: always
    depends_on:
      - postgres
    ports:
      - ${DJANGO_PORT}:8000
    volumes:
      - .:/var/www/django
    working_dir: "/var/www/django"
    command: gunicorn DRF.wsgi -b restful01-django:8000
    networks:
      - django-network

  mongo:
    image: mongo:8-noble
    container_name: mongodb-gisa
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    restart: always

  postgres:
    image: postgres:17-alpine
    container_name: postgresql-gisa
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:5432
    networks:
      - django-network

  nginx:
    image: nginx:1.26-alpine
    container_name: nginx-gisa
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    restart: always
